src/Entity/Commande.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommandeRepository")
 */
class Commande
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ref;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ipClient;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Article", inversedBy="commandes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Article;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\PaymentCommande", inversedBy="commande", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $paymentCommande;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $beDownload;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $ipDownload;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRef(): ?string
    {
        return $this->ref;
    }

    public function setRef(string $ref): self
    {
        $this->ref = $ref;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getIpClient(): ?string
    {
        return $this->ipClient;
    }

    public function setIpClient(string $ipClient): self
    {
        $this->ipClient = $ipClient;

        return $this;
    }

    public function getArticle(): ?Article
    {
        return $this->Article;
    }

    public function setArticle(?Article $Article): self
    {
        $this->Article = $Article;

        return $this;
    }

    public function getPaymentCommande(): ?PaymentCommande
    {
        return $this->paymentCommande;
    }

    public function setPaymentCommande(PaymentCommande $paymentCommande): self
    {
        $this->paymentCommande = $paymentCommande;

        return $this;
    }

    public function getBeDownload(): ?bool
    {
        return $this->beDownload;
    }

    public function setBeDownload(?bool $beDownload): self
    {
        $this->beDownload = $beDownload;

        return $this;
    }

    public function getIpDownload(): ?string
    {
        return $this->ipDownload;
    }

    public function setIpDownload(?string $ipDownload): self
    {
        $this->ipDownload = $ipDownload;

        return $this;
    }
}

src/Controller/CommandeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Commande;
use Symfony\Component\HttpFoundation\JsonResponse;

class CommandeController extends AbstractController
{
    /**
     * @Route("/commande-source/{ref}", name="commande-source")
     */
    public function comSource($ref = null)
    {
        if($ref != null){
          //Commande
          $repo = $this->getDoctrine()->getRepository(Commande::class);
          $commandeFound = $repo->createQueryBuilder('c')
                                        ->where('c.ref = :ref')
                                        ->setParameter('ref', $ref)
                                        ->setMaxResults(1)
                                        ->getQuery()
                                        ->getOneOrNullResult();

          if($commandeFound != null){
              if($commandeFound->getBeDownload() == 1){
                // ERROR Déjà téléharger
                $this->addFlash('warning', 'Le fichier dont vous essayez d\'avoir l\'accès a déjà été téléchargé, si vous pensez qu\'il s\'agit d\'une erreur veuillez nous contacter.');
                return $this->redirectToRoute('404');
              }
          } else {
            //ERROR commande inexistante
            $this->addFlash('warning', 'Cette commande est inexistante, si vous pensez qu\'il s\'agit d\'une erreur veuillez nous contacter.');
            return $this->redirectToRoute('404');
          }

        } else {
          // ERROR PAGE AUCUNE REF
          $this->addFlash('warning', 'Aucune référence n\'a été renseignée.');
          return $this->redirectToRoute('404');
        }

        //Afficher page pour download
        return $this->render('commande/index.html.twig', [
            'controller_name' => 'Téléchargez le code source',
            'commande' => $commandeFound,
        ]);
    }

    /**
     * @Route("/commande-checked/{ref}", name="commande-checked")
     */
    public function comChecked($ref = null, Request $request, ObjectManager $manager)
    {
      //IF AJAX
      if($request->isXmlHttpRequest()){
          if($ref != null){
            //Commande
            $repo = $this->getDoctrine()->getRepository(Commande::class);
            $commandeFound = $repo->createQueryBuilder('c')
                                          ->where('c.ref = :ref')
                                          ->setParameter('ref', $ref)
                                          ->setMaxResults(1)
                                          ->getQuery()
                                          ->getOneOrNullResult();

            if($commandeFound != null){
                //CHECKED
                $commandeFound->setBeDownload(1)
                              ->setIpDownload($request->getClientIp());
                $manager->persist($commandeFound);
                $manager->flush();
                return new JsonResponse(1);
            } else {
              //ERROR commande inexistante
              return new JsonResponse("Commande inexistante.");
            }

          } else {
            // ERROR PAGE 404
            return new JsonResponse("Référence de la commande non-renseignée.");
          }
      }

      //Afficher page pour download
      return $this->render('main/error_404.html.twig', [
          'controller_name' => 'Page introuvable',
      ]);
    }
}

templates/commande/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ controller_name }}{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{{asset('assets/css/download.css')}}">
{% endblock %}

{% block body %}
<section class="s-content s-content--top-padding s-content--narrow">

  <div class="row narrow">
      <div class="col-full s-content__header">
          <h1 class="display-1 display-1--with-line-sep" style="font-size:2em;">Téléchargez votre fichier en cliquant sur la flèche ci-dessous.</h1>
          <p class="lead" style="font-size:1em;">
          Attention, une fois téléchargé vous ne pourrez plus acceder à cette page pour des raisons de sécurité !</p>
      </div>
  </div>

  <div class="container-fluid">
  	<div class="row">
  		<div id="ms-container">
  			<label for="ms-download" class="ms-download">
  				<div class="ms-content">
  					<div class="ms-content-inside">
  						<input type="checkbox" id="ms-download" />
  						<div class="ms-line-down-container">
  							<div class="ms-line-down"></div>
  						</div>
  						<div class="ms-line-point"></div>
  					</div>
  				</div>
  			</label>
  		</div>
  	</div>
  </div>
</section>
{% endblock %}

{% block javascripts %}
<script type="text/javascript">
  $("#ms-download").click(function(){
    if($(this).is(":checked")){
      //GO LINK DOWNLOAD
      window.open('{{asset(commande.article.source)}}', '_blank');
      // AJAX CHECK BEDOWNLOAD IN COMMANDE
      $.ajax({
          async: true,
          type: 'POST',
          url: "{{ path('commande-checked', {"ref": commande.ref}) }}",
          success: function (data) {
              if(data != 1){
                window.location.reload();
              }
          },
      });
    }
  })
</script>
{% endblock %}